### PR TITLE
Spline Noise Modifier

### PR DESCRIPTION
**Pull request by pixel-ninja**
A modifier for adding noise and spirals along splines.
I'll add help docs if you're keen to add it.

Also displays a functioning group selection method that might be worth incorporating in the other MOPs (as group selection currently seems to be broken in all of the MOPs I've tried).

mops_splinenoise_ref

Note: Created with a limited commercial license, so will need conversion

### CODE REVIEW

**Comment by pixel-ninja** [comment]
Built this on 16.5.496.
Just tried to test on 16.5.268 and a lot of functionality is broken. I'll need to figure out why...

**Comment by pixel-ninja** [comment]
All fixed. Apparently the "Arc Length Spline" option in the uvtexture node works for nurbs AND polys in 16.5.496.
Prior to this it only worked for nurbs, completely overlooked that.

**Comment by toadstorm** [comment]
Group selection was a bit screwed because of a bad Python script in Apply Attributes; that's since been fixed. The automatic point group conversion is a good idea, though.

This Spline Noise seems like it would be pretty handy. I did notice that the Spiral doesn't work correctly if the input curve is not parallel with the Z-axis, unless I resample the line first (not counting the internal Resample in your HDA). Moving the Resample to happen before the Polyframe / Parallel Transport appears to solve this.

I'll keep testing and tweaking this; the UI might be a little bit busy but the functionality is great!

**Comment by pixel-ninja** [comment]
Ah yeah, the Parallel Transport was struggling to calculate straight lines, I added a point jitter to give it some help, but that still requires a line with at least 3 points. The noise will have the same issue if "Orient Noise" is checked.
The resample was after because I was getting some slightly jagged results from Parallel Transport with it the other way around for some reason... Probably requires investigation.

I agree about the UI, I do have a tendency to over promote parameters.
In hindsight there's really no reason that the noise and spirals have to be in one node. They could always be split into their own operators, which would simplify it a bit.

Awesome. If you want a hand with anything let me know. Happy to help out :)

**Pull request closed without merging**
